datasource:
  config:
    master:
      driver: com.mysql.cj.jdbc.Driver
      password: XXX
      url: XXX
      userName: XXX
server:
  port: 8900
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848