datasource:
  config:
    master:
      driver: com.mysql.cj.jdbc.Driver
      password: XXX
      url: XXX
      userName: XXX
server:
  port: 8901
  servlet:
    context-path: /forum
spring:
  application:
    name: forummain
  cloud:
    nacos:
      server-addr: localhost:8848
  profiles:
    active: dev
logging:
  level:
    com.hpstudio.forummain: debug
